config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root "news#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    # get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'gallery', to: 'gallery#index'
  resources :users, only: %i[show]
  namespace :user do
    resources :pictures, only: %i[new create]
  end

  namespace :admin do
    get '/', to: 'admin#index'
    resources :municipalities, only: %i[index edit update]
    resources :news, only: %i[index update]
    resources :news_sources, only: %i[index show new create edit update]
  end

  # For all users
  resources :news, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include ArticleImageUploader[:image]
  belongs_to :user

  validates :user, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  # include ImageUploader::Attachment.new(:image) # adds an 'image' virtual attribute
  include ImageUploader[:image]

  belongs_to :user
  validates :title, :date, :address, presence: true

end

app/models/municipality.rb
class Municipality < ApplicationRecord
  belongs_to :state
  has_many :news
  has_many :pictures
  has_one_attached :logo
end

app/models/news.rb
# frozen_string_literal: true

# News model class
class News < ApplicationRecord
  PER_PAGE = 5

  belongs_to :municipality
  belongs_to :news_source, optional: true

  has_one_attached :image

  enum status: { unpublished: 0, published: 1 }

  validates_presence_of :title
end

app/models/news_source.rb
class NewsSource < ApplicationRecord
  has_many :news
  has_one_attached :logo

  validates_presence_of :name, :url
end

app/models/photo.rb
class Photo < ApplicationRecord
  include PhotoUploader[:photo]
  include Likeable
  belongs_to :user

  validates :photo, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :municipality
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :small, resize_to_limit: [200, 200]
    attachable.variant :normal, resize_to_limit: [500, 500]
    attachable.variant :large, resize_to_limit: [1000, 1000]
  end

  validates :image, presence: true, blob: { content_type: :image, size_range: 1..(10.megabytes) }
end

app/models/privacy_policy.rb
class PrivacyPolicy < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :pictures, dependent: :destroy

  enum role: { user: 0, admin: 99 }

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    find_or_create_by(email: email) do |user|
      user.uid = uid,
      user.full_name = full_name
      user.avatar_url = avatar_url
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def users
    @users = User.order(created_at: 'desc')
  end

  def application_settings
    @application_settings = ApplicationSetting.all
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_link_for(target)
    link_to "like it!!", like_path(:resource_name => target.class, :resource_id => target.id), :method => :post
  end

  def unlike_link_for(target)
    link_to "unlike it!!", like_path(:resource_name => target.class, :resource_id => target.id), :method => :delete
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/_nav.html.erb
<nav>
  <div class="nav-wrapper grey darken-3">
    <%= link_to 'Dashboard', dashboard_index_path, class: 'brand-logo' %>
    <ul class="right hide-on-med-and-down">
      <li>
        <%= link_to privacy_policies_path do %>
          Politicas de Privacidad<i class="material-icons left">library_books</i>  
        <% end %>
        Link with Left Icon
      </li>
      <li>
        <%= link_to dashboard_users_path do %>
          Usuarios<i class="material-icons left">people</i>  
        <% end %>
        Link with Left Icon
      </li>
      <li>
        <%= link_to dashboard_application_settings_path do%>
          <i class="material-icons left">settings</i>Configuraciones
        <% end %>
      </li>
      <li>
        <%= link_to sidekiq_web_path, target: '_blank' do %>
          Sidekiq<i class="material-icons right">av_timer</i>  
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/dashboard/application_settings.html.erb
<%= render 'nav' %>
<div class="container">
  <div class="row">
    <div class="col s12">
      <h1 class="center">Configuraciones de Aplicación</h1>
    </div>

    <div class="col s12 l8 offset-l2">
      <table class="striped">
        <thead>
          <tr class="blue-grey darken-1 white-text">
            <th>Configuración</th>
            <th>Valor</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @application_settings.each do |application_setting| %>
            <tr>
              <td><%= application_setting.setting %></td>
              <td><%= application_setting.value %></td>
              <td><%= link_to 'Cambiar', edit_application_setting_path(application_setting), class: 'btn' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'nav' %>

<div class="container">
  <div class="row">

    <div class="col s12 m12 l12">

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="card-panel teal">
            <h4 class="white-text">
              <strong><%= PrivacyPolicy.count %></strong>
              P. de privacidad
            </h4>

            <%= link_to 'Ver', privacy_policies_path, class: 'btn white black-text' %>
          </div>
        </div>
      </div>

    </div>

    <div class="col s12 m12 l12">
      <div class="row">
        <div class="col s12 m5 l4">
          <div class="card-panel teal">
            <h4 class="white-text">
              <strong><%= PrivacyPolicy.count %></strong>
              Usuarios
            </h4>

            <%= link_to 'Ver', dashboard_users_path, class: 'btn white black-text' %>

          </div>
        </div>
      </div>
    </div>

    <div class="col s12 m12 l12">

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="card-panel teal">
            <h4 class="white-text">
              <strong><%= PrivacyPolicy.count %></strong>
              Configuraciones
            </h4>

            <%= link_to 'Ver', dashboard_application_settings_path, class: 'btn white black-text' %>

          </div>
        </div>
      </div>
    </div>

    <div class="col s12 m12 l12">

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="card-panel teal">
            <h4 class="white-text">
              <strong></strong>
              Sideqik ejecuciones <small>Ultimos 5 dias</small>
            </h4>
            <% Sidekiq::Stats::History.new(4).processed.each do |day| %>
              <p class="white-text"><%= "#{day[0]}: #{day[1]}" %></p>
            <% end %>

            <%= link_to 'Ver', sidekiq_web_path, class: 'btn white black-text' %>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/users.html.erb
<%= render 'nav' %>
<div class="container">
  <div class="row">
    <div class="col s12">
      <h1>Usuarios</h1>
      <table class="striped">
        <thead>
          <tr class="blue-grey darken-1 white-text">
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Ingreso</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <% if user.image.present? %>
                <%= image_tag user.image %>
              <% else %>
                <%= image_tag 'blank_profile_small.png' %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>