config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root "news#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    # get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'gallery', to: 'gallery#index'
  resources :users, only: %i[show]
  namespace :user do
    resources :pictures, only: %i[new create]
  end

  namespace :admin do
    get '/', to: 'admin#index'
    resources :municipalities, only: %i[index edit update]
    resources :news, only: %i[index update]
    resources :news_sources, only: %i[index show new create edit update]
  end

  # For all users
  resources :news, only: %i[index show]
end

app/models/article.rb
class Article < ApplicationRecord
  include ArticleImageUploader[:image]
  belongs_to :user

  validates :user, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  # include ImageUploader::Attachment.new(:image) # adds an 'image' virtual attribute
  include ImageUploader[:image]

  belongs_to :user
  validates :title, :date, :address, presence: true

end

app/models/municipality.rb
class Municipality < ApplicationRecord
  belongs_to :state
  has_many :news
  has_many :pictures
  has_one_attached :logo
end

app/models/news.rb
# frozen_string_literal: true

# News model class
class News < ApplicationRecord
  PER_PAGE = 5

  belongs_to :municipality
  belongs_to :news_source, optional: true

  has_one_attached :image

  enum status: { unpublished: 0, published: 1 }

  validates_presence_of :title
end

app/models/news_source.rb
class NewsSource < ApplicationRecord
  has_many :news
  has_one_attached :logo

  validates_presence_of :name, :url
end

app/models/photo.rb
class Photo < ApplicationRecord
  include PhotoUploader[:photo]
  include Likeable
  belongs_to :user

  validates :photo, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :municipality
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :small, resize_to_limit: [200, 200]
    attachable.variant :normal, resize_to_limit: [500, 500]
    attachable.variant :large, resize_to_limit: [1000, 1000]
  end

  validates :image, presence: true, blob: { content_type: :image, size_range: 1..(10.megabytes) }
end

app/models/privacy_policy.rb
class PrivacyPolicy < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :pictures, dependent: :destroy

  enum role: { user: 0, admin: 99 }

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    find_or_create_by(email: email) do |user|
      user.uid = uid,
      user.full_name = full_name
      user.avatar_url = avatar_url
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_link_for(target)
    link_to "like it!!", like_path(:resource_name => target.class, :resource_id => target.id), :method => :post
  end

  def unlike_link_for(target)
    link_to "unlike it!!", like_path(:resource_name => target.class, :resource_id => target.id), :method => :delete
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admin/index.html.slim
h1 Panel de Administradores
p Aquí puedes adminsitrar todo lo referente a la aplicación ;)

app/views/shared/_admin_header.html.slim
header.header
  .brand
    .header__brand
      = link_to root_path do
        h1 Admin Panel
  .menu
    nav
      ul
        li = link_to 'Municipios', admin_municipalities_url
        li = link_to 'Noticias', admin_news_index_url
        li = link_to 'Fuentes Noticias', admin_news_sources_url
  .user
    = link_to 'Admin', admin_url
    = link_to current_user do
      = image_tag current_user.avatar_url, class: 'header__user-avatar'
    = link_to "Salir", destroy_user_session_path

app/views/shared/_header.html.slim
header.header
  .header__brand
    = link_to root_path do
      = image_tag municipality.logo.variant(resize_to_limit: [100, 100]) if municipality.logo.present?
      h1 = municipality.name
  .header__user
    - unless current_user
      = button_to "Google Login",
                user_google_oauth2_omniauth_authorize_path,
                class: 'btn btn--primary',
                method: :post,
                data: { turbo: false }
    - else
      = link_to 'Admin', admin_url
      = link_to current_user do
        = image_tag current_user.avatar_url, class: 'header__user-avatar'

app/views/shared/_nav.html.slim
nav.menu
  ul
    li> = link_to "📰 Noticias", root_path
    li< = link_to "🖼️ Fotos", gallery_path